### PR TITLE
fix(shield): fix nil env dereference panic

### LINKED ISSUE #360: Shield.Eval nil pointer dereference
Shield.Eval method panics with `nil pointer dereference` in case of `nil` `env Environment` arg.

We need to deal with this case and throw an error rather than panicking

### PR DESCRIPTION
**Pull request by optifat**
closes #360

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed an issue in the shield module to handle nil environments, preventing potential application crashes.

- **Tests**
  - Added a new test to verify the proper handling of nil environments in the evaluation process.

### CODE REVIEW

File: shield/internal/evaluator/evaluator.go [hunk 1]
```diff
@@ -35,6 +35,12 @@ func Eval(exp *ast.Expression, env env.Environment) object.Object {
 			return v
 		}
 
+		if env == nil {
+			return &object.Error{
+				Message: fmt.Sprintf("unknown identifier '%s': passed environment is nil", exp.Identifier.Value),
+			}
+		}
+
```
Comment (pitasi) [inline shield/internal/evaluator/evaluator.go]:
```suggestion
		if env == nil {
			return newError("unknown identifier '%s': passed environment is nil", exp.Identifier.Value)
		}
```

for consistency :)

**Review by pitasi — CHANGES_REQUESTED** [review]

**Review by pitasi — APPROVED** [review]
lgtm
