### PR TITLE
fix(shield): add unit tests for ASP preprocess

### LINKED ISSUE #140: Add Unit Tests for Preprocess Function in preprocess.go
This issue tracks the task of ensuring the correctness of the preprocessing logic by adding unit tests for the  function and its helper functions, as discussed in the pull request review.

Context:
- Pull Request: https://github.com/warden-protocol/wardenprotocol/pull/139
- Comment: https://github.com/warden-protocol/wardenprotocol/pull/139#discussion_r1549911517

The unit tests should cover various scenarios to validate the functionality of the  function and its helper functions within .

### PR DESCRIPTION
**Pull request by Overseven**
closes #140 

## Summary by CodeRabbit

- **Tests**
  - Added unit tests for the AST preprocessor in the shield module.

### CODE REVIEW

File: shield/internal/preprocess/preprocess_test.go [hunk 1]
```diff
@@ -0,0 +1,124 @@
+package preprocess
+
+import (
+	"context"
+	"github.com/stretchr/testify/require"
+	"github.com/warden-protocol/wardenprotocol/shield/ast"
+	"github.com/warden-protocol/wardenprotocol/shield/internal/lexer"
+	"github.com/warden-protocol/wardenprotocol/shield/internal/parser"
+	"github.com/warden-protocol/wardenprotocol/warden/x/intent/cosmoshield"
```
Comment (pitasi) [inline shield/internal/preprocess/preprocess_test.go]: I think that the `shield` package shouldn't depend on anything else.

From what I see below, all the tests are using a no-op expander, so instead of using cosmoshield we can reimplement it like this:

```go
type NoopExpander struct{}

func (n NoopExpander) Expand(context.Context, ident *ast.Identifier) {
    return ast.NewIdentifier(ident)
}
```

**Review by pitasi — CHANGES_REQUESTED** [review]
thanks for starting these new unit tests!

File: shield/internal/preprocess/preprocess_test.go (hunk 1 above)
Comment (Overseven) [reply shield/internal/preprocess/preprocess_test.go]: Done

**Comment by pitasi** [comment]
thanks, one last nit: could you squash the two commits into a single one to keep git history clean?

**Comment by Overseven** [comment]
> thanks, one last nit: could you squash the two commits into a single one to keep git history clean?

How exactly should I do this? "Squash and merge" PR option is disabled for this repo. Should I create a new PR?

Screenshot 2024-05-29 at 12 09 34

**Comment by pitasi** [comment]
> > thanks, one last nit: could you squash the two commits into a single one to keep git history clean?
> 
> How exactly should I do this? "Squash and merge" PR option is disabled for this repo. Should I create a new PR?

No problem! In this case, what I would do (locally) is this:

- move to your branch
```
git switch feature/ast-preprocess-unit-tests
```

- rebase interactively to `main`:
```
git rebase -i main
```

- it will open a text editor with the following content:
```
pick 3d85ea3a fix(shield): add unit tests for ASP preprocess
pick 02f26da9 fix(shield): add NoopExpander
```

- edit the second line like this:
```
pick 3d85ea3a fix(shield): add unit tests for ASP preprocess
f 02f26da9 fix(shield): add NoopExpander
```

(`f` stands for `fixup` = merge that commit into the commit above)

- save and close the file
- you can check the result with `git log` if you want, you should see a single commit in your branch
- push the result (requires `-f` but I usually do `--force-with-lease` instead, which is a bit safer since it aborts if you're overriding someone else's commits!)
```
git push --force-with-lease
```

we have some more guides here https://docs.wardenprotocol.org/developers/contributing/#clean-up-mistakes-by-rewriting-history that explains possible alternatives on how to achieve this :)

hope it helps

**Comment by Overseven** [comment]
@Pitasi Done!

**Review by pitasi — APPROVED** [review]
